### ISSUE TITLE
Feature request - ability to use custom faraday middleware

### ISSUE THREAD

**Issue by daisy1754** [checkout/checkout-sdk-ruby#51]
In our application, we use inhouse faraday middleware called RequestMetricsMiddleware to instrument all outgoing request. It would be great if user of library can use custom middleware eg

```
Checkout.new(config) do |builder|
  builder.use RequestMetricsMiddleware
end
```

**Comment by Armando-Ibarra** [comment]
Hi @daisy1754 

Sorry to circle back too late on this, but we just released a new version for Ruby SDK
https://github.com/checkout/checkout-sdk-ruby/releases/tag/1.0.0

Which includes a lot of new functionalities for previous and default version, you can see the README for more details.

Including the feature to provide your own http client, just check the README to double-check what are the configuration that you need to consider in order to do that, let us know if you have any issues
